export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transcations with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Piggybank',
    dark: false,
    primary: false,
    // darkText: true,
}

export const homeObjThree = {
    id: 'newsletter',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Stay Updated',
    headline: 'Subscribe to our newsletter',
    description: 'Subscribe to our newsletter and receive the latest news',
    buttonLabel: 'Subscribe',
    imgStart: false,
    img: require('../../images/svg-6.svg').default,
    alt: 'Newsletter',
    dark: false,
    primary: false,
    darkText: true,
}